# NOTE: this template will be evaluated by eval.Env first
#       make sure we have matrix related variables resolved now

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name@template: |-
    {{- trimPrefix "kubectl-" env.APP -}}
spec:
  version: ${VERSION}
  homepage: ${HOMEPAGE}
  shortDescription: |-
    {{- env.SHORT_DESCRIPTION | default env.APP -}}
  description@template?str: |-
    {{- env.DESCRIPTION -}}
  caveats@template?str: |-
    {{- env.CAVEATES -}}
  platforms@!:
    value: []
    merge@template: |-
      {{- \$entries :=
          split (
            eval.Shell
              (printf "find build/manifests -mindepth 1 -maxdepth 1 -type f -name '%s.*.yml'" env.APP)
          ) "\n"
      -}}
      {{- range \$_, \$v := \$entries }}
        {{- if \$v }}
      - value@file: {{ \$v | trimPrefix "build/manifests/" }}
        {{- end }}
      {{- end }}
